### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by evsyukovmv** [evsyukovmv/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by evsyukov-m** [comment]
+380987654321
[yoda@example.com](mailto:yoda@example.com)
Yoda on [Wikipedia](http://en.wikipedia.org/wiki/Wikipedia)
Yoda at the [Internet Movie Database](http://en.wikipedia.org/wiki/Internet_Movie_Database)
