### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by evsyukovmv** [evsyukovmv/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by evsyukov-m** [comment]
Born 900 years before the Battle of Endor, Yoda belonged to an ancient and mysterious species and never revealed his homeworld. As he was keenly attuned to the Force, he joined the Jedi Order as a youngling. After undergoing the ritual known as the Gathering, he received his kyber crystal, and Professor Huyang helped him construct his first lightsaber aboard the Crucible. At some point during his time as a youngling, Yoda skipped across the lily pads in the Jedi Temple's meditation pond. Yoda was paired up with a personal mentor. During their time together, Yoda's Jedi Master told him the tale of K'ungfu and Chuang, two great Jedi of the past. Around the age of 100, Yoda was ready to pass on what he had learned. Having attained the rank of Master, he spent the next eight centuries training and tutoring generations of Jedi. It was estimated that over his lifetime, he trained around 20,000 Jedi.

In 232 BBY, Yoda went with Grand Master Pra-Tre Veter to Starlight Beacon. There, they named Master Avar Kriss as the Marshal of Starlight Beacon. He later attended the Beacon's dedication ceremony.

Centuries later, Yoda took on the human Dooku as his last known Padawan in the era of the Galactic Republic. While Dooku initially wanted to become the Padawan of Lene Kostana, his upset subsided when he learned he would be Yoda's apprentice. During one mission to the Wookiee homeworld of Kashyyyk, the Padawan witnessed his master face off with a giant, dreadful terentatek.

Yoda visited Kashyyyk on several other occasions prior to the Battle of Kashyyyk, serving as Jedi negotiator in many incidents involving the Wookiees and their Trandoshan neighbors. This earned him the ancient title of "Defender of the Home Tree," as well as becoming a member of many Wookiee leaders' and all the inhabitants of Kachirho's honor families.

Yoda also taught outside the Master/Padawan relationship, and trained all the Jedi younglings prior to their teaming up with Jedi Masters, including Master Obi-Wan Kenobi. Kanan Jarrus, as Caleb Dume, often heard Yoda counsel, "Do, or do not. There is no try." He also taught groups of younglings in the basics of Jedi training, including lightsaber instruction.
