### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by evsyukovmv** [evsyukovmv/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by evsyukov-m** [comment]
Yoda Quotes:

“Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering.”
“Once you start down the dark path, forever will it dominate your destiny. Consume you, it will.”
“Always pass on what you have learned.”
“Patience you must have my young Padawan.”
“In a dark place we find ourselves, and a little more knowledge lights our way.”
“Death is a natural part of life. Rejoice for those around you who transform into the Force. Mourn them do not. Miss them do not. Attachment leads to jealously. The shadow of greed, that is.”
“Powerful you have become, the dark side I sense in you.”
